name: meaning_mate
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_crashlytics: ^4.3.0
  page_transition: ^2.2.1
  permission_handler: ^11.3.1
  change_app_package_name: ^1.4.0
  provider: ^6.1.2
  introduction_screen: ^3.1.14
  flutter_svg: ^2.0.17
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  cloud_firestore: ^5.6.1
  shared_preferences: ^2.3.5
  fuzzy: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
