name: meaning_mate
description: "Your Pocket Vocabulary Trainer"
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_crashlytics: ^4.3.0
  page_transition: ^2.2.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  introduction_screen: ^3.1.14
  flutter_svg: ^2.0.17
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  cloud_firestore: ^5.6.1
  shared_preferences: ^2.3.5
  fuzzy: ^0.5.1
  google_fonts: ^6.2.1
  package_info_plus: ^8.1.3
  flutter_gemini: ^3.0.0
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.2.1
  shorebird_code_push: ^2.0.0
  flutter_markdown: ^0.7.5
  word_generator: ^0.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/icon/
    - shorebird.yaml

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
