name: Dart and Flutter Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analysis:
    runs-on: ubuntu-latest

    name: Code Analysis
    steps:
      - name: Update & Upgrade System
        run: sudo apt-get update -y && sudo apt-get upgrade -y

      - name: git-checkout
        uses: actions/checkout@v4

      - name: Flutter setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      - name: Flutter Install Project Dependencies
        run: flutter pub get

      - name: Analyze Flutter Code
        run: flutter analyze
